name: Run Unit Test via Pytest (Poetry)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.6"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
            java-version: 11
      - name: Setup Spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.5.0'
          hadoop-version: '3'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry first
        run: pip install poetry
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip pandas 
          poetry install --with dev
      - name: Lint with Ruff
        run: |  
          pip install ruff  
          ruff --format=github --target-version=py311 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          poetry run coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: |  
          poetry run coverage report -m